apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: '25%'
      maxSurge: '25%'
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      dnsPolicy: ClusterFirst
      securityContext:  
        runAsNonRoot: true
      containers:
      - image: redis
        name: redis
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.5"
            memory: "100Mi"
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - echo
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
