apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: '25%'
      maxSurge: '25%'
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      dnsPolicy: ClusterFirst
      securityContext:  
        runAsNonRoot: true
      containers:
      - image: quay.io/oktaysavdi/probe@sha256:fa2598896bd57c11b04acd4c50509e69d9e691b01f7d5d49fada512177bdaee9
        name: project1
        imagePullPolicy: Always
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.5"
            memory: "100Mi"
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 5
