apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: '25%'
      maxSurge: '25%'
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      dnsPolicy: ClusterFirst
      securityContext:  
        runAsNonRoot: true
      containers:
      - image: quay.io/oktaysavdi/istioproject@sha256:e92c62f3de5048b1583f5ede446005f64c3d7154fcd39ce7ab4765e490f3cdea
        name: project2
        imagePullPolicy: Always
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.5"
            memory: "100Mi"
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - echo
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
