apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: '25%'
      maxSurge: '25%'
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      dnsPolicy: ClusterFirst
      securityContext:  
        runAsNonRoot: true
      containers:
      - image: quay.io/oktaysavdi/istioproject@sha256:070cf43b432e2c98a1747e1c19de25abf3ebf631b65434cc59f512c3de513581
        name: project2
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.5"
            memory: "100Mi"
        readinessProbe:
          exec:
            command:
            - ls
            - /opt
          initialDelaySeconds: 10
          periodSeconds: 15
        livenessProbe:
          exec:
            command:
            - ls
            - /opt
          initialDelaySeconds: 10
          periodSeconds: 15 
